### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by trllnd** [trllnd/shodo-simulator#1]
```css
li {
  animation-name: animateIn;
  animation-duration: .64s; 
  animation-delay: calc(var(--animation-order) * .64s);
  animation-fill-mode: both;
  animation-timing-function: ease-in-out;
}

/* li + li {
  margin-top: 16px;
} */

@keyframes animateIn {
    0% { opacity: 0; }
  100% { opacity: 1; }
}

```
